# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  REPO_URL: $REPO_URL

tasks:
  build-cli:
    desc: Build the CLI application
    cmds:
      - go build -ldflags "-X consts.RepoURL={{.REPO_URL}}" -o bin/dsy ./apps/cli
    silent: true

  generate-slqc:
    desc: Generate the SQLc code
    dir: ./apps/backend
    cmds:
      - sqlc generate
    silent: true

  run-dev-detached:
    desc: Run the development environment detached using podman compose
    cmds:
      - podman compose -f docker-compose.dev.yml up -d --build
    silent: true
