// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CliToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Token      string             `json:"token"`
	DeviceName pgtype.Text        `json:"device_name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Installer struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Category    string             `json:"category"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InstallerScript struct {
	ID                pgtype.UUID        `json:"id"`
	InstallerID       pgtype.UUID        `json:"installer_id"`
	OsFamily          string             `json:"os_family"`
	ShellType         string             `json:"shell_type"`
	PreInstallScript  pgtype.Text        `json:"pre_install_script"`
	MainInstallScript string             `json:"main_install_script"`
	PostInstallScript pgtype.Text        `json:"post_install_script"`
	UninstallScript   pgtype.Text        `json:"uninstall_script"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProfileInstaller struct {
	ProfileID      pgtype.UUID `json:"profile_id"`
	InstallerID    pgtype.UUID `json:"installer_id"`
	ExecutionOrder int32       `json:"execution_order"`
}

type ProfileRepository struct {
	ProfileID         pgtype.UUID `json:"profile_id"`
	RepositoryID      pgtype.UUID `json:"repository_id"`
	PreInstallScript  pgtype.Text `json:"pre_install_script"`
	PostInstallScript pgtype.Text `json:"post_install_script"`
	TargetDirectory   string      `json:"target_directory"`
	Branch            string      `json:"branch"`
}

type Repository struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	RepoUrl    string             `json:"repo_url"`
	Branch     string             `json:"branch"`
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	PasswordHash  string             `json:"password_hash"`
	Banned        bool               `json:"banned"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserPasswordReset struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserSession struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SessionStart pgtype.Timestamptz `json:"session_start"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
}

type UserVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
