// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CliToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Token      string
	DeviceName pgtype.Text
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Installer struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	Category    string
	Visibility  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type InstallerScript struct {
	ID                pgtype.UUID
	InstallerID       pgtype.UUID
	OsFamily          string
	ShellType         string
	PreInstallScript  pgtype.Text
	MainInstallScript string
	PostInstallScript pgtype.Text
	UninstallScript   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Profile struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Visibility  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProfileInstaller struct {
	ProfileID      pgtype.UUID
	InstallerID    pgtype.UUID
	ExecutionOrder int32
}

type ProfileRepository struct {
	ProfileID       pgtype.UUID
	RepositoryID    pgtype.UUID
	TargetDirectory string
	Branch          string
}

type Repository struct {
	ID         pgtype.UUID
	ProfileID  pgtype.UUID
	RepoUrl    string
	Branch     string
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Name          pgtype.Text
	Username      string
	Email         string
	EmailVerified pgtype.Bool
	PasswordHash  string
	Banned        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
