// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserPasswordResetsByUserID = `-- name: DeleteUserPasswordResetsByUserID :exec
DELETE FROM user_password_reset WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordResetsByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResetsByUserID, userID)
	return err
}

const getUserPasswordResetByTokenHash = `-- name: GetUserPasswordResetByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM user_password_reset WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetUserPasswordResetByTokenHash(ctx context.Context, tokenHash string) (UserPasswordReset, error) {
	row := q.db.QueryRow(ctx, getUserPasswordResetByTokenHash, tokenHash)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserPasswordReset = `-- name: InsertUserPasswordReset :one
INSERT INTO user_password_reset (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type InsertUserPasswordResetParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertUserPasswordReset(ctx context.Context, arg InsertUserPasswordResetParams) (UserPasswordReset, error) {
	row := q.db.QueryRow(ctx, insertUserPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
