// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_refresh_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserRefreshTokenByRefreshTokenHash = `-- name: DeleteUserRefreshTokenByRefreshTokenHash :exec
DELETE FROM user_refresh_token WHERE token_hash = $1
`

func (q *Queries) DeleteUserRefreshTokenByRefreshTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokenByRefreshTokenHash, tokenHash)
	return err
}

const deleteUserRefreshTokensByUserID = `-- name: DeleteUserRefreshTokensByUserID :exec
DELETE FROM user_refresh_token WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokensByUserID, userID)
	return err
}

const getUserRefreshTokenByRefreshTokenHash = `-- name: GetUserRefreshTokenByRefreshTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM user_refresh_token WHERE token_hash = $1
`

func (q *Queries) GetUserRefreshTokenByRefreshTokenHash(ctx context.Context, tokenHash string) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, getUserRefreshTokenByRefreshTokenHash, tokenHash)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserRefreshToken = `-- name: InsertUserRefreshToken :one
INSERT INTO user_refresh_token (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type InsertUserRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertUserRefreshToken(ctx context.Context, arg InsertUserRefreshTokenParams) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertUserRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
