// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :one
UPDATE "user"
SET
    banned = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

func (q *Queries) BanUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, banUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE username = $1 LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsernameOrEmail = `-- name: FindUserByUsernameOrEmail :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE username = $1 OR email = $1 LIMIT 1
`

func (q *Queries) FindUserByUsernameOrEmail(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsernameOrEmail, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

type InsertUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET
    username = $1,
    email = $2,
    email_verified = $3,
    banned = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

type UpdateUserParams struct {
	Username      string
	Email         string
	EmailVerified pgtype.Bool
	Banned        bool
	ID            pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.Banned,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserWithPassword = `-- name: UpdateUserWithPassword :one
UPDATE "user"
SET
    username = $1,
    email = $2,
    password_hash = $3,
    email_verified = $4,
    banned = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

type UpdateUserWithPasswordParams struct {
	Username      string
	Email         string
	PasswordHash  string
	EmailVerified pgtype.Bool
	Banned        bool
	ID            pgtype.UUID
}

func (q *Queries) UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserWithPassword,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.Banned,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE "user"
SET
    email_verified = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
