// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_verification_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserVerificationTokensByUserID = `-- name: DeleteUserVerificationTokensByUserID :exec
DELETE FROM user_verification_token WHERE user_id = $1
`

func (q *Queries) DeleteUserVerificationTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserVerificationTokensByUserID, userID)
	return err
}

const getUserVerificationTokenByHash = `-- name: GetUserVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM user_verification_token WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetUserVerificationTokenByHash(ctx context.Context, tokenHash string) (UserVerificationToken, error) {
	row := q.db.QueryRow(ctx, getUserVerificationTokenByHash, tokenHash)
	var i UserVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserVerificationToken = `-- name: InsertUserVerificationToken :one
INSERT INTO user_verification_token (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type InsertUserVerificationTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertUserVerificationToken(ctx context.Context, arg InsertUserVerificationTokenParams) (UserVerificationToken, error) {
	row := q.db.QueryRow(ctx, insertUserVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
