// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE "user"
SET
    banned = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) BanUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, banUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, name, username, email, email_verified, password_hash, banned, created_at, updated_at FROM "user" WHERE username = $1 OR email = $1 LIMIT 1
`

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (username, email, email_verified, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, name, username, email, email_verified, password_hash, banned, created_at, updated_at
`

type InsertUserParams struct {
	Username      string
	Email         string
	EmailVerified bool
	PasswordHash  string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.PasswordHash,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET
    username = $1,
    email = $2,
    email_verified = $3,
    banned = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateUserParams struct {
	Username      string
	Email         string
	EmailVerified bool
	Banned        bool
	ID            pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.Banned,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE "user"
SET
    password_hash = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE "user"
SET
    email_verified = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
