// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/mennaverse/dotsync/apps/backend/db"
	"github.com/mennaverse/dotsync/apps/backend/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticationService creates a new instance of MockAuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticationService {
	mock := &MockAuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticationService is an autogenerated mock type for the AuthenticationService type
type MockAuthenticationService struct {
	mock.Mock
}

type MockAuthenticationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticationService) EXPECT() *MockAuthenticationService_Expecter {
	return &MockAuthenticationService_Expecter{mock: &_m.Mock}
}

// ForgotPassword provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) ForgotPassword(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockAuthenticationService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthenticationService_Expecter) ForgotPassword(ctx any, email any) *MockAuthenticationService_ForgotPassword_Call {
	return &MockAuthenticationService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, email)}
}

func (_c *MockAuthenticationService_ForgotPassword_Call) Run(run func(ctx context.Context, email string)) *MockAuthenticationService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_ForgotPassword_Call) Return(err error) *MockAuthenticationService_ForgotPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthenticationService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) Login(ctx context.Context, req *dto.LoginRequest) (*dto.TokenPair, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest) (*dto.TokenPair, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest) *dto.TokenPair); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticationService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthenticationService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.LoginRequest
func (_e *MockAuthenticationService_Expecter) Login(ctx any, req any) *MockAuthenticationService_Login_Call {
	return &MockAuthenticationService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthenticationService_Login_Call) Run(run func(ctx context.Context, req *dto.LoginRequest)) *MockAuthenticationService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_Login_Call) Return(tokenPair *dto.TokenPair, err error) *MockAuthenticationService_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthenticationService_Login_Call) RunAndReturn(run func(ctx context.Context, req *dto.LoginRequest) (*dto.TokenPair, error)) *MockAuthenticationService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthenticationService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthenticationService_Expecter) Logout(ctx any, refreshToken any) *MockAuthenticationService_Logout_Call {
	return &MockAuthenticationService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthenticationService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthenticationService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_Logout_Call) Return(err error) *MockAuthenticationService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockAuthenticationService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAllSessions provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) LogoutAllSessions(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_LogoutAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAllSessions'
type MockAuthenticationService_LogoutAllSessions_Call struct {
	*mock.Call
}

// LogoutAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthenticationService_Expecter) LogoutAllSessions(ctx any, userID any) *MockAuthenticationService_LogoutAllSessions_Call {
	return &MockAuthenticationService_LogoutAllSessions_Call{Call: _e.mock.On("LogoutAllSessions", ctx, userID)}
}

func (_c *MockAuthenticationService_LogoutAllSessions_Call) Run(run func(ctx context.Context, userID string)) *MockAuthenticationService_LogoutAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_LogoutAllSessions_Call) Return(err error) *MockAuthenticationService_LogoutAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_LogoutAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockAuthenticationService_LogoutAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) RefreshToken(ctx context.Context, refreshToken string) (*dto.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticationService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthenticationService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthenticationService_Expecter) RefreshToken(ctx any, refreshToken any) *MockAuthenticationService_RefreshToken_Call {
	return &MockAuthenticationService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthenticationService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthenticationService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_RefreshToken_Call) Return(tokenPair *dto.TokenPair, err error) *MockAuthenticationService_RefreshToken_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthenticationService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*dto.TokenPair, error)) *MockAuthenticationService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) Register(ctx context.Context, req *dto.RegisterRequest) (*db.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) (*db.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterRequest) *db.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticationService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthenticationService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RegisterRequest
func (_e *MockAuthenticationService_Expecter) Register(ctx any, req any) *MockAuthenticationService_Register_Call {
	return &MockAuthenticationService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthenticationService_Register_Call) Run(run func(ctx context.Context, req *dto.RegisterRequest)) *MockAuthenticationService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_Register_Call) Return(user *db.User, err error) *MockAuthenticationService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthenticationService_Register_Call) RunAndReturn(run func(ctx context.Context, req *dto.RegisterRequest) (*db.User, error)) *MockAuthenticationService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerificationEmail provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) ResendVerificationEmail(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerificationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_ResendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerificationEmail'
type MockAuthenticationService_ResendVerificationEmail_Call struct {
	*mock.Call
}

// ResendVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthenticationService_Expecter) ResendVerificationEmail(ctx any, email any) *MockAuthenticationService_ResendVerificationEmail_Call {
	return &MockAuthenticationService_ResendVerificationEmail_Call{Call: _e.mock.On("ResendVerificationEmail", ctx, email)}
}

func (_c *MockAuthenticationService_ResendVerificationEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthenticationService_ResendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_ResendVerificationEmail_Call) Return(err error) *MockAuthenticationService_ResendVerificationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_ResendVerificationEmail_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthenticationService_ResendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) ResetPassword(ctx context.Context, token string, newPassword string) error {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthenticationService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockAuthenticationService_Expecter) ResetPassword(ctx any, token any, newPassword any) *MockAuthenticationService_ResetPassword_Call {
	return &MockAuthenticationService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *MockAuthenticationService_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockAuthenticationService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_ResetPassword_Call) Return(err error) *MockAuthenticationService_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) error) *MockAuthenticationService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) ValidateAccessToken(ctx context.Context, accessToken string) (*dto.Claims, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *dto.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.Claims, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.Claims); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticationService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAuthenticationService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockAuthenticationService_Expecter) ValidateAccessToken(ctx any, accessToken any) *MockAuthenticationService_ValidateAccessToken_Call {
	return &MockAuthenticationService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, accessToken)}
}

func (_c *MockAuthenticationService_ValidateAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockAuthenticationService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_ValidateAccessToken_Call) Return(claims *dto.Claims, err error) *MockAuthenticationService_ValidateAccessToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockAuthenticationService_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (*dto.Claims, error)) *MockAuthenticationService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type MockAuthenticationService
func (_mock *MockAuthenticationService) VerifyEmail(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticationService_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthenticationService_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthenticationService_Expecter) VerifyEmail(ctx any, token any) *MockAuthenticationService_VerifyEmail_Call {
	return &MockAuthenticationService_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *MockAuthenticationService_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *MockAuthenticationService_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticationService_VerifyEmail_Call) Return(err error) *MockAuthenticationService_VerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticationService_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthenticationService_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
