/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LogoutRouteImport } from "./routes/logout"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as HomeRouteImport } from "./routes/home"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AUsernameRouteImport } from "./routes/a/$username"
import { Route as AUsernameRepositoryRouteImport } from "./routes/a/$username/repository"
import { Route as AUsernameProfileRouteImport } from "./routes/a/$username/profile"
import { Route as AUsernameInstallerRouteImport } from "./routes/a/$username/installer"
import { Route as AUsernameRepositoryRepositoryRouteImport } from "./routes/a/$username/repository/$repository"
import { Route as AUsernameProfileProfileRouteImport } from "./routes/a/$username/profile/$profile"
import { Route as AUsernameInstallerInstallerRouteImport } from "./routes/a/$username/installer/$installer"
import { Route as AUsernameProfileProfileEditRouteImport } from "./routes/a/$username/profile/$profile/edit"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AUsernameRoute = AUsernameRouteImport.update({
  id: "/a/$username",
  path: "/a/$username",
  getParentRoute: () => rootRouteImport,
} as any)
const AUsernameRepositoryRoute = AUsernameRepositoryRouteImport.update({
  id: "/repository",
  path: "/repository",
  getParentRoute: () => AUsernameRoute,
} as any)
const AUsernameProfileRoute = AUsernameProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AUsernameRoute,
} as any)
const AUsernameInstallerRoute = AUsernameInstallerRouteImport.update({
  id: "/installer",
  path: "/installer",
  getParentRoute: () => AUsernameRoute,
} as any)
const AUsernameRepositoryRepositoryRoute =
  AUsernameRepositoryRepositoryRouteImport.update({
    id: "/$repository",
    path: "/$repository",
    getParentRoute: () => AUsernameRepositoryRoute,
  } as any)
const AUsernameProfileProfileRoute = AUsernameProfileProfileRouteImport.update({
  id: "/$profile",
  path: "/$profile",
  getParentRoute: () => AUsernameProfileRoute,
} as any)
const AUsernameInstallerInstallerRoute =
  AUsernameInstallerInstallerRouteImport.update({
    id: "/$installer",
    path: "/$installer",
    getParentRoute: () => AUsernameInstallerRoute,
  } as any)
const AUsernameProfileProfileEditRoute =
  AUsernameProfileProfileEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => AUsernameProfileProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/a/$username": typeof AUsernameRouteWithChildren
  "/a/$username/installer": typeof AUsernameInstallerRouteWithChildren
  "/a/$username/profile": typeof AUsernameProfileRouteWithChildren
  "/a/$username/repository": typeof AUsernameRepositoryRouteWithChildren
  "/a/$username/installer/$installer": typeof AUsernameInstallerInstallerRoute
  "/a/$username/profile/$profile": typeof AUsernameProfileProfileRouteWithChildren
  "/a/$username/repository/$repository": typeof AUsernameRepositoryRepositoryRoute
  "/a/$username/profile/$profile/edit": typeof AUsernameProfileProfileEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/a/$username": typeof AUsernameRouteWithChildren
  "/a/$username/installer": typeof AUsernameInstallerRouteWithChildren
  "/a/$username/profile": typeof AUsernameProfileRouteWithChildren
  "/a/$username/repository": typeof AUsernameRepositoryRouteWithChildren
  "/a/$username/installer/$installer": typeof AUsernameInstallerInstallerRoute
  "/a/$username/profile/$profile": typeof AUsernameProfileProfileRouteWithChildren
  "/a/$username/repository/$repository": typeof AUsernameRepositoryRepositoryRoute
  "/a/$username/profile/$profile/edit": typeof AUsernameProfileProfileEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/a/$username": typeof AUsernameRouteWithChildren
  "/a/$username/installer": typeof AUsernameInstallerRouteWithChildren
  "/a/$username/profile": typeof AUsernameProfileRouteWithChildren
  "/a/$username/repository": typeof AUsernameRepositoryRouteWithChildren
  "/a/$username/installer/$installer": typeof AUsernameInstallerInstallerRoute
  "/a/$username/profile/$profile": typeof AUsernameProfileProfileRouteWithChildren
  "/a/$username/repository/$repository": typeof AUsernameRepositoryRepositoryRoute
  "/a/$username/profile/$profile/edit": typeof AUsernameProfileProfileEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/a/$username"
    | "/a/$username/installer"
    | "/a/$username/profile"
    | "/a/$username/repository"
    | "/a/$username/installer/$installer"
    | "/a/$username/profile/$profile"
    | "/a/$username/repository/$repository"
    | "/a/$username/profile/$profile/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/a/$username"
    | "/a/$username/installer"
    | "/a/$username/profile"
    | "/a/$username/repository"
    | "/a/$username/installer/$installer"
    | "/a/$username/profile/$profile"
    | "/a/$username/repository/$repository"
    | "/a/$username/profile/$profile/edit"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/a/$username"
    | "/a/$username/installer"
    | "/a/$username/profile"
    | "/a/$username/repository"
    | "/a/$username/installer/$installer"
    | "/a/$username/profile/$profile"
    | "/a/$username/repository/$repository"
    | "/a/$username/profile/$profile/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AUsernameRoute: typeof AUsernameRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logout": {
      id: "/logout"
      path: "/logout"
      fullPath: "/logout"
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/home": {
      id: "/home"
      path: "/home"
      fullPath: "/home"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/a/$username": {
      id: "/a/$username"
      path: "/a/$username"
      fullPath: "/a/$username"
      preLoaderRoute: typeof AUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/a/$username/repository": {
      id: "/a/$username/repository"
      path: "/repository"
      fullPath: "/a/$username/repository"
      preLoaderRoute: typeof AUsernameRepositoryRouteImport
      parentRoute: typeof AUsernameRoute
    }
    "/a/$username/profile": {
      id: "/a/$username/profile"
      path: "/profile"
      fullPath: "/a/$username/profile"
      preLoaderRoute: typeof AUsernameProfileRouteImport
      parentRoute: typeof AUsernameRoute
    }
    "/a/$username/installer": {
      id: "/a/$username/installer"
      path: "/installer"
      fullPath: "/a/$username/installer"
      preLoaderRoute: typeof AUsernameInstallerRouteImport
      parentRoute: typeof AUsernameRoute
    }
    "/a/$username/repository/$repository": {
      id: "/a/$username/repository/$repository"
      path: "/$repository"
      fullPath: "/a/$username/repository/$repository"
      preLoaderRoute: typeof AUsernameRepositoryRepositoryRouteImport
      parentRoute: typeof AUsernameRepositoryRoute
    }
    "/a/$username/profile/$profile": {
      id: "/a/$username/profile/$profile"
      path: "/$profile"
      fullPath: "/a/$username/profile/$profile"
      preLoaderRoute: typeof AUsernameProfileProfileRouteImport
      parentRoute: typeof AUsernameProfileRoute
    }
    "/a/$username/installer/$installer": {
      id: "/a/$username/installer/$installer"
      path: "/$installer"
      fullPath: "/a/$username/installer/$installer"
      preLoaderRoute: typeof AUsernameInstallerInstallerRouteImport
      parentRoute: typeof AUsernameInstallerRoute
    }
    "/a/$username/profile/$profile/edit": {
      id: "/a/$username/profile/$profile/edit"
      path: "/edit"
      fullPath: "/a/$username/profile/$profile/edit"
      preLoaderRoute: typeof AUsernameProfileProfileEditRouteImport
      parentRoute: typeof AUsernameProfileProfileRoute
    }
  }
}

interface AUsernameInstallerRouteChildren {
  AUsernameInstallerInstallerRoute: typeof AUsernameInstallerInstallerRoute
}

const AUsernameInstallerRouteChildren: AUsernameInstallerRouteChildren = {
  AUsernameInstallerInstallerRoute: AUsernameInstallerInstallerRoute,
}

const AUsernameInstallerRouteWithChildren =
  AUsernameInstallerRoute._addFileChildren(AUsernameInstallerRouteChildren)

interface AUsernameProfileProfileRouteChildren {
  AUsernameProfileProfileEditRoute: typeof AUsernameProfileProfileEditRoute
}

const AUsernameProfileProfileRouteChildren: AUsernameProfileProfileRouteChildren =
  {
    AUsernameProfileProfileEditRoute: AUsernameProfileProfileEditRoute,
  }

const AUsernameProfileProfileRouteWithChildren =
  AUsernameProfileProfileRoute._addFileChildren(
    AUsernameProfileProfileRouteChildren,
  )

interface AUsernameProfileRouteChildren {
  AUsernameProfileProfileRoute: typeof AUsernameProfileProfileRouteWithChildren
}

const AUsernameProfileRouteChildren: AUsernameProfileRouteChildren = {
  AUsernameProfileProfileRoute: AUsernameProfileProfileRouteWithChildren,
}

const AUsernameProfileRouteWithChildren =
  AUsernameProfileRoute._addFileChildren(AUsernameProfileRouteChildren)

interface AUsernameRepositoryRouteChildren {
  AUsernameRepositoryRepositoryRoute: typeof AUsernameRepositoryRepositoryRoute
}

const AUsernameRepositoryRouteChildren: AUsernameRepositoryRouteChildren = {
  AUsernameRepositoryRepositoryRoute: AUsernameRepositoryRepositoryRoute,
}

const AUsernameRepositoryRouteWithChildren =
  AUsernameRepositoryRoute._addFileChildren(AUsernameRepositoryRouteChildren)

interface AUsernameRouteChildren {
  AUsernameInstallerRoute: typeof AUsernameInstallerRouteWithChildren
  AUsernameProfileRoute: typeof AUsernameProfileRouteWithChildren
  AUsernameRepositoryRoute: typeof AUsernameRepositoryRouteWithChildren
}

const AUsernameRouteChildren: AUsernameRouteChildren = {
  AUsernameInstallerRoute: AUsernameInstallerRouteWithChildren,
  AUsernameProfileRoute: AUsernameProfileRouteWithChildren,
  AUsernameRepositoryRoute: AUsernameRepositoryRouteWithChildren,
}

const AUsernameRouteWithChildren = AUsernameRoute._addFileChildren(
  AUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AUsernameRoute: AUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
