/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LogoutRouteImport } from "./routes/logout"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as HomeRouteImport } from "./routes/home"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProfileUsernameRouteImport } from "./routes/profile/$username"
import { Route as ProfileUsernameRepositoriesRouteImport } from "./routes/profile/$username/repositories"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: "/profile/$username",
  path: "/profile/$username",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRepositoriesRoute =
  ProfileUsernameRepositoriesRouteImport.update({
    id: "/repositories",
    path: "/repositories",
    getParentRoute: () => ProfileUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/profile/$username": typeof ProfileUsernameRouteWithChildren
  "/profile/$username/repositories": typeof ProfileUsernameRepositoriesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/profile/$username": typeof ProfileUsernameRouteWithChildren
  "/profile/$username/repositories": typeof ProfileUsernameRepositoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/home": typeof HomeRoute
  "/login": typeof LoginRoute
  "/logout": typeof LogoutRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/verify-email": typeof VerifyEmailRoute
  "/profile/$username": typeof ProfileUsernameRouteWithChildren
  "/profile/$username/repositories": typeof ProfileUsernameRepositoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/profile/$username"
    | "/profile/$username/repositories"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/profile/$username"
    | "/profile/$username/repositories"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/home"
    | "/login"
    | "/logout"
    | "/register"
    | "/search"
    | "/verify-email"
    | "/profile/$username"
    | "/profile/$username/repositories"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ProfileUsernameRoute: typeof ProfileUsernameRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logout": {
      id: "/logout"
      path: "/logout"
      fullPath: "/logout"
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/home": {
      id: "/home"
      path: "/home"
      fullPath: "/home"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/$username": {
      id: "/profile/$username"
      path: "/profile/$username"
      fullPath: "/profile/$username"
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/$username/repositories": {
      id: "/profile/$username/repositories"
      path: "/repositories"
      fullPath: "/profile/$username/repositories"
      preLoaderRoute: typeof ProfileUsernameRepositoriesRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
  }
}

interface ProfileUsernameRouteChildren {
  ProfileUsernameRepositoriesRoute: typeof ProfileUsernameRepositoriesRoute
}

const ProfileUsernameRouteChildren: ProfileUsernameRouteChildren = {
  ProfileUsernameRepositoriesRoute: ProfileUsernameRepositoriesRoute,
}

const ProfileUsernameRouteWithChildren = ProfileUsernameRoute._addFileChildren(
  ProfileUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ProfileUsernameRoute: ProfileUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
